name: Generate Documentation

on:
  push:
    branches:
      - master

jobs:
  generate-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Get the code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Generate documentation
        run: python scripts/generate_docs.py